
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace hikaya_Ajloun.Models
{

using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Article
{

    public int articleId { get; set; }

    public string articleName { get; set; }

    public string articleImage { get; set; }

    public Nullable<int> categoryId { get; set; }

        [AllowHtml]
    public string articleFile { get; set; }

    public Nullable<System.DateTime> articleDate { get; set; }

    public int authorid { get; set; }



    public virtual author author { get; set; }

    public virtual Category Category { get; set; }

}

}
