//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hikaya_Ajloun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkout
    {
        public int orderId { get; set; }
        public Nullable<int> totalAmount { get; set; }
        public Nullable<int> orderDate { get; set; }
        public Nullable<int> address_2 { get; set; }
        public Nullable<int> address_1 { get; set; }
        public Nullable<int> email { get; set; }
        public Nullable<int> phoneNumber { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Payment_Mthod { get; set; }
        public Nullable<int> city { get; set; }
        public string user_id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
