
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace hikaya_Ajloun.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Comment
{

    public int id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Comment1 { get; set; }

    public Nullable<bool> status { get; set; }

    public Nullable<int> articalid { get; set; }



    public virtual Article Article { get; set; }

}

}
