
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace hikaya_Ajloun.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Order()
    {

        this.Order_Details = new HashSet<Order_Details>();

    }


    public int orderId { get; set; }

    public Nullable<int> totalAmount { get; set; }

    public Nullable<int> orderDate { get; set; }

    public Nullable<int> address_2 { get; set; }

    public Nullable<int> address_1 { get; set; }

    public Nullable<int> email { get; set; }

    public Nullable<int> phoneNumber { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string Payment_Mthod { get; set; }

    public Nullable<int> city { get; set; }

    public string User_id { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Order_Details> Order_Details { get; set; }

}

}
