//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hikaya_Ajloun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class place
    {
        public int placeId { get; set; }
        public int placeName { get; set; }
        public int placeImage1 { get; set; }
        public int placeImage2 { get; set; }
        public int placeImage3 { get; set; }
        public int placeImage4 { get; set; }
        public int placeImage5 { get; set; }
        public int categoryId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
