
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace hikaya_Ajloun.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ProductsRequest
{

    public int id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string ProductName { get; set; }

    public string Adress1 { get; set; }

    public string Adress2 { get; set; }

    public string Message { get; set; }

    public string image1 { get; set; }

    public string image2 { get; set; }

    public string image3 { get; set; }

    public string image4 { get; set; }

}

}
