
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace hikaya_Ajloun.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Product
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product()
    {

        this.Carts = new HashSet<Cart>();

        this.Order_Details = new HashSet<Order_Details>();

    }


    public int productId { get; set; }

    public string productName { get; set; }

    public string productImage_1 { get; set; }

    public string productImage_2 { get; set; }

    public string productImage_3 { get; set; }

    public string productImage_4 { get; set; }

    public string productImage_5 { get; set; }

    public int price { get; set; }

    public string productDescription { get; set; }

    public int categoryId { get; set; }

    public string availability { get; set; }

    public string shipping_return { get; set; }

    public Nullable<int> reviewid { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Cart> Carts { get; set; }

    public virtual Category Category { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Order_Details> Order_Details { get; set; }

    public virtual Review Review { get; set; }

}

}
