
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace hikaya_Ajloun.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Profile
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Profile()
    {

        this.Orders = new HashSet<Order>();

    }


    public string id { get; set; }

    public string First_Name { get; set; }

    public string Last_Name { get; set; }

    public string Adress1 { get; set; }

    public string Adress2 { get; set; }

    public Nullable<int> ZIP_Code { get; set; }

    public string City { get; set; }

    public Nullable<int> Phone_Number { get; set; }

    public string userid { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Order> Orders { get; set; }

}

}
