
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace hikaya_Ajloun.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Review
{

    public int reviewId { get; set; }

    public int productId { get; set; }

    public string comment { get; set; }

    public string userName { get; set; }

    public string userImage { get; set; }

    public string User_id { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    public virtual Product Product { get; set; }

}

}
