
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace hikaya_Ajloun.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Order_Details
{

    public int OrderDetails_id { get; set; }

    public Nullable<int> Order_id { get; set; }

    public Nullable<int> Product_id { get; set; }

    public Nullable<int> Quantity { get; set; }



    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }

}

}
